Backport 63f8fc87cdf3edb828474bb4954b76721ba8f9e5
openjdk/jdk16u pull request #94
Opened 2021-03-26 21:26 UTC by RealCLanger

2021-03-31 20:16 UTC, phohensee requested changes
In SSLSocketImpl.java, lines 1480-1484 are replaced by a single line 1488, but the original patch doesn't do that. SSLTransport.java needs a copyright update to 2021. Otherwise, lgtm.

2021-04-01 11:19 UTC, RealCLanger commented
> In SSLSocketImpl.java, lines 1480-1484 are replaced by a single line 1488, but the original patch doesn't do that. SSLTransport.java needs a copyright update to 2021. Otherwise, lgtm.

OK, the change l 1480-1484 comes from https://bugs.openjdk.java.net/browse/JDK-8253635 which in itself probably makes sense to backport as well. But I took it out for this BP.

I updated copyright years for both, SSLTransport and SSLSocketImpl.

2021-04-01 14:40 UTC, phohensee approved these changes

2021-04-01 20:35 UTC, RealCLanger commented
/integrate

2021-04-01 20:36 UTC, closed without merging